### ISSUE TITLE
redis.close() ; - error, 'class Redis' has no member 'close'

### ISSUE THREAD

**Issue by metcalfepete** [electric-sheep-co/arduino-redis#26]
Hi,
Thanks for the great redis library for Arduino. 

With the simple and pubsub examples I get an error on: redis.close() 

 'class Redis' has no member 'close' 

I comment out this line and it works fine, but for long term scheduled communications I thought that it might be safer to open/close the connect as required. 

Would you have any suggestions?

Again thanks for the excellent library.

Regards
Pete

**Comment by rpj** [comment]
Hi Pete,

First, thank you so much for the kind words & I'm really glad to hear the library is serving you well! I'm a huge fan of Redis myself and originally wrote this library for personal use, but as it grew I really did hope others would find it useful as well.

As for the issue you found: great catch! I admit that I hadn't personally run those examples in awhile (my bad!!) and indeed you are correct that the `Redis` class has no `close()` method any longer and therefore that call is invalid.

In reality, when I decided to further build out this library I tried to do so in a loosely-coupled way, in order to make it as useful as possible. Accordingly, I modified the way the `Redis` class itself works, having it now [accept as a constructor parameter the `Stream` instance](http://arduino-redis.com/classRedis.html#a1b5c1cc8b21c8b5ca48e70c017479df4) ([source](https://github.com/electric-sheep-co/arduino-redis/blob/master/Redis.h#L45-L50)) to be used for the underlying raw communication between server and client. In this way, you could use the `Redis` client class with Ethernet or any other `Stream`-subclassed implementation.

This implementation also allows you to specifically and granularly control lifetime of the underlying `Stream` independent on the `Redis` protocol client instance itself. And in fact that's exactly [the fix I've made to the examples](https://github.com/electric-sheep-co/arduino-redis/pull/27/commits/e24f04337b59ec0d8095bbec4148bdce6efd0f23#diff-604b2e2a66e2977a9aca002ceeb94eadR59) to address this issue.

I've checked in those fixes as #27 and will be putting together a new dot-release version of the library soon, so please stay tuned to the Arduino Library Manager for an update.

Thank you again Pete and please don't hesitate to get in touch again if you have any other trouble or questions!

**Comment by rpj** [comment]
[Version 2.1.3](https://github.com/electric-sheep-co/arduino-redis/releases/tag/2.1.3) should show up in the Arduino Library Manager within an hour or two! Thanks again Pete

**Comment by metcalfepete** [comment]
Ryan,

Thanks for sending me an update.

I think that you've done a really nice job on the Arduino Redis library. Like you I'm a big fan of Redis and I'm super happy to use your library with my Arduino projects.

Have yourself a great weekend
Regards
Pete

________________________________
