### ISSUE TITLE
Support for  Subscribe

### ISSUE THREAD

**Issue by stochasticForest** [electric-sheep-co/arduino-redis#28]
Great library, I may have missed it, but I don't see an implementation for the subscribe function on the Arduino.

I'm trying to implement a system where an IoT device waits for triggers from a server and this
would be very useful.

Is it likely it might be implemented any time soon ? 

Thanks.

**Comment by rpj** [comment]
Thanks very much for the kind words @stochasticForest, much appreciated!

You have a good eye, indeed there is no implementation in this library for the [`subscribe` command](https://redis.io/commands/subscribe), and that's for a couple of reasons. First, as you can see from the docs, once `subscribe` is issued the client is transitioned into a different mode, making it no longer capable of acting as a general Redis client.

With Arduino lacking support for any concurrency (threading or otherwise), it's a bit of a challenge to implement a "subscribe-mode" Redis client in Arduino while still allowing other logic to be executed. 

It is of course possible, in a number of ways in fact, but that's where the other reason comes in: admittedly I've written this library organically according to the needs of [a personal project of mine](https://github.com/rpj/zw), and as such simply haven't spent the time working out this particular challenge (as I haven't needed it myself yet).

That said, now that I know someone else needs this functionality I'll bump it to the top of my priority list for this project, but unfortunately this project itself is a hobby as well so I can't promise any particular timeline.

Of course you're always more than welcome to put together a `subscribe` API and submit a pull request, I'd love to have more folks working on this library with me!

If you do end up taking a crack at it, I'm absolutely happy to answer any questions and help in any way I can, time allowing.

Thanks again!
-RPJ

**Comment by rpj** [comment]
Oh and also @stochasticForest - geez how did I forget to mention this! - there's actually another Redis client library I've been working on called [`yarl`](https://github.com/electric-sheep-co/yarl/), written in C and intended to eventually become the foundation of *this* library. 

Moreover, that library *does* have an implementation of [`subscribe`](https://github.com/electric-sheep-co/yarl/blob/master/src/commands.h#L44-L46) and there's even a working example of multiple uses of it in [this project](https://github.com/rpj/spheremon), specifically starting [here](https://github.com/rpj/spheremon/blob/master/spheremon/main.c#L233) & [here](https://github.com/rpj/spheremon/blob/master/spheremon/main.c#L263).

However, as you'll probably quickly note, the platform that latter project is running on *does* have proper threading support (`pthreads` FTW) so it is utilizing them to manage the fact that `yarl` client objects transition into that aforementioned "subscription" special mode.

Not sure how helpful it would be in implementing something targeted for Arduino, but I thought it couldn't hurt.

**Comment by yakovlevyuri** [comment]
Hi @rpj I would also need this functionality :)

**Comment by svdasein** [comment]
@rpj I also would love to have subscribe functionality in this library.  I actually hacked together something that sorta worked, but I am absolutely not a C/C++ guy so I'm really a drunk bull in a china shop with this stuff.

I'm gathering by the code in this library on the other hand that you are quite adept at C++, so I'm wondering if you could answer this:

Is it possible to use your library to parse messages from the server as they'd come to you from a subscription?  Specifially I'm wondering if one could do something like 

if (redisClientConnectionBytes.available()) 
     result = YourRedisLibrary.consumeMessageFrom(redisClientBytes)

I can see you're doing all kinds of magic with types in there so I'm not really sure how this'd actually work (if indeed the functions you've got in your library can do this).  But - if there is a way, could you give me a few pointers as to what it might look like?

Thanks

**Comment by rpj** [comment]
@stochasticForest @yakovlevyuri @svdasein Many apologies for how long it took to finally get this implemented, but I'm happy to let you know that this feature is now available in version **2.2.0** (available in the Arduino library manager soon).

Given the aforementioned restrictions with the Arduino runtime being single-threaded, I decided to take the simple route and make the interface blocking: a successful call to the [`startSubscribing()`](http://arduino-redis.com/classRedis.html#a8d192249d02ef9f493c2a0c52c515e7e) method will *block* (preventing `loop()` from being called), with the message handler callbacks becoming the "loop" code paths.

A full example of this usage is available in [this new example](https://github.com/electric-sheep-co/arduino-redis/blob/master/examples/Subscribe/Subscribe.ino): as you'll see it is using closures (lambda functions) as the handlers but those could as easily be defined as bonafide functions if that is preferred.

Please do file a new issue with _any_ trouble or bugs your encounter while using this new functionality, as well as if you have any feedback on the interface and/or usage model. There are many ways this could've been implemented, and while I'm not certain the one I've chosen here is _best_, I do think it's simplicity is beneficial (to ease implementation on both the library & consumer sides, if anything).

Thank you all so much for you feedback, engagement & support! I don't have much time to focus on this library, but I assure you it is _not_ abandoned at all, just slow-moving 😄
